export const styles = {
  page: {
    maxWidth: 680,
    margin: "0 auto",
    padding: "2rem 1.2rem",
    minHeight: "100vh",
  },
  card: {
    background: "#fff",
    border: "1px solid #E8ECF4",
    borderRadius: 14,
    padding: "1.6rem",
    marginBottom: "1rem",
  },
  input: {
    width: "100%",
    padding: "0.6rem 0.9rem",
    border: "1px solid #D1D9E6",
    borderRadius: 8,
    fontSize: "0.88rem",
    outline: "none",
    transition: "border-color 0.15s",
    background: "#fff",
  },
  label: {
    display: "block",
    fontSize: "0.78rem",
    fontWeight: 600,
    color: "#374151",
    marginBottom: 5,
    letterSpacing: "0.02em",
  },
  btnPrimary: {
    background: "#1a1a2e",
    color: "#fff",
    border: "none",
    borderRadius: 9,
    padding: "0.65rem 1.4rem",
    fontSize: "0.85rem",
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 0.15s",
    width: "100%",
  },
  btnSecondary: {
    background: "#fff",
    color: "#1a1a2e",
    border: "1px solid #D1D9E6",
    borderRadius: 9,
    padding: "0.6rem 1.2rem",
    fontSize: "0.85rem",
    fontWeight: 500,
    cursor: "pointer",
    width: "100%",
  },
  btnIndigo: {
    background: "#4F46E5",
    color: "#fff",
    border: "none",
    borderRadius: 9,
    padding: "0.65rem 1.4rem",
    fontSize: "0.85rem",
    fontWeight: 600,
    cursor: "pointer",
    width: "100%",
  },
  divider: {
    border: "none",
    borderTop: "1px solid #E8ECF4",
    margin: "1rem 0",
  },
  metric: {
    background: "#F8F9FC",
    border: "1px solid #E8ECF4",
    borderRadius: 10,
    padding: "0.8rem 1rem",
    textAlign: "center",
  },
  metricValue: {
    fontSize: "1.5rem",
    fontWeight: 700,
    color: "#1a1a2e",
    fontFamily: "'Space Grotesk', sans-serif",
  },
  metricLabel: {
    fontSize: "0.7rem",
    color: "#6B7280",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginTop: 2,
  },
  badge: (color) => ({
    display: "inline-block",
    padding: "2px 10px",
    borderRadius: 20,
    fontSize: "0.72rem",
    fontWeight: 600,
    background:
      color === "green" ? "#D1FAE5" : color === "red" ? "#FEE2E2" : "#E0E7FF",
    color:
      color === "green" ? "#065F46" : color === "red" ? "#991B1B" : "#3730A3",
  }),
  alert: (type) => ({
    padding: "0.65rem 0.9rem",
    borderRadius: 8,
    fontSize: "0.82rem",
    marginBottom: "0.8rem",
    background:
      type === "error" ? "#FEF2F2" : type === "success" ? "#F0FDF4" : "#EFF6FF",
    color:
      type === "error" ? "#B91C1C" : type === "success" ? "#166534" : "#1D4ED8",
    border: `1px solid ${type === "error" ? "#FECACA" : type === "success" ? "#BBF7D0" : "#BFDBFE"}`,
  }),
};
